update tuples with composite keys
tarantool-php/client pull request #14
Opened 2016-10-29 21:16 UTC by nekufa

UpdateRequest implementation contains array wrapper for the primary key.
In this case, i unable to make an update of the tuple with composite key.

I added the check, to keep backward compatibility.

2016-10-30 14:07 UTC, rybakit commented
@nekufa could you please add an integration test for the issue?

2016-10-30 19:12 UTC, rybakit requested changes

2016-10-30 19:12 UTC, rybakit commented on src/Request/UpdateRequest.php
> +            IProto::KEY => is_array($this->key) ? $this->key : [$this->key],
I would move this check to the constructor.

2016-10-31 09:49 UTC, nekufa commented
@rybakit yep, but a bit later

2016-11-02 12:54 UTC, rybakit commented on src/Request/UpdateRequest.php
> +            IProto::KEY => is_array($this->key) ? $this->key : [$this->key],
@nekufa I checked other requests which deal with keys:
https://github.com/tarantool-php/client/blob/master/src/Request/SelectRequest.php#L16
https://github.com/tarantool-php/client/blob/master/src/Request/DeleteRequest.php#L13
To keep it consistent, UpdateRequest's constructor should expect `array $key`, or other requests should be updated to work with both scalar and array arguments. Not sure which option is preferable ;)

2016-11-30 20:59 UTC, merged

2016-11-30 20:59 UTC, rybakit commented
@nekufa Thanks!